name: 'build-test'
on:
  pull_request:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          node --version
          npm install
      - run: |
          npm run all
      - run: |
          npm run test
  run-self:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: get_changed
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          foldersOnly: true
      - name: Echo
        run: echo ${{ steps.get_changed.outputs.changed }}
